services:
  app:
    build: 
      context: .
      target: app
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - backend

  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${SQL_USER:-postgres}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-postgres}
      POSTGRES_DB: ${SQL_DATABASE:-postgres}
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
